name: main
on:
  schedule:
  - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git config --global user.name 'Github Actions'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: |
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
          git remote set-url upstream https://x-access-token:$GH_TOKEN@github.com/dotnet/format
          git fetch upstream
          git merge upstream/master
          git push origin HEAD:refs/heads/main --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
